In [58]:
import numpy as np

In [1]:
# search the array to find an empty box
# empty box is identified as 0 in the grid

def find_empty_box(arr, loc):
    for row in range(9):
        for col in range(9):
            if arr[row][col] == 0:
                loc[0] = row
                loc[1] = col
                return True
    return False

In [21]:
# check if the number already exists in row

def num_in_row(arr, row, num):
    if num in arr[row]:
        return True
    return False

In [22]:
# check if the number already exists in column

def num_in_col(arr, col, num):
    for i in range(9):
        if(arr[i][col] == num):
            return True
    return False

In [23]:
# check if the number exists in the 3x3 sub-array

def num_in_box(arr, row, col, num):
    for i in range(3):
        for j in range(3):
            if arr[row+i][col+j] == num:
                return True
    return False

In [24]:
# call function to validate all rules

def check(arr, row, col, num):
    return not num_in_row(arr, row, num) and not num_in_col(arr, col, num) and not num_in_box(arr, row-row%3, col-col%3, num)

In [25]:
def sudoku_solver(arr):
    
    # initialize loc variable which travels the grid
    loc = [0,0]
    
    # check if loc represents an empty box
    if(not find_empty_box(arr, loc)):
        return True
     
    # Assigning list values to row and col that we got from the above Function
    row = loc[0]
    col = loc[1]
     
    # consider digits 1 to 9
    for num in range(1, 10):
        if(check(arr,row, col, num)):
             
            # tentatively assign num to box
            arr[row][col]= num
 
            # recursively call the sudoku_solver() to check if it satisfies the conditions with new number added.
            # if all the boxes are filled recursively and the conditions are satisifed, we break from the loop and return True
            if(sudoku_solver(arr)):
                return True
 
            # else, we reassign the tentative num back to 0 and try again
            arr[row][col] = 0
             
    # there is no solution for the given sudoku problem     
    return False

In [59]:
grid =[[0 for x in range(9)]for y in range(9)]

# assigning values to the grid
grid =[[3, 0, 6, 5, 0, 8, 4, 0, 0],
      [5, 2, 0, 0, 0, 0, 0, 0, 0],
      [0, 8, 7, 0, 0, 0, 0, 3, 1],
      [0, 0, 3, 0, 1, 0, 0, 8, 0],
      [9, 0, 0, 8, 6, 3, 0, 0, 5],
      [0, 5, 0, 0, 9, 0, 6, 0, 0],
      [1, 3, 0, 0, 0, 0, 2, 5, 0],
      [0, 0, 0, 0, 0, 0, 0, 7, 4],
      [0, 0, 5, 2, 0, 6, 3, 0, 0]]

# if success print the grid
if(sudoku_solver(grid)):
    print(np.array(grid))
else:
    print ("No solution exists")

[[3 1 6 5 7 8 4 9 2]
 [5 2 9 1 3 4 7 6 8]
 [4 8 7 6 2 9 5 3 1]
 [2 6 3 4 1 5 9 8 7]
 [9 7 4 8 6 3 1 2 5]
 [8 5 1 7 9 2 6 4 3]
 [1 3 8 9 4 7 2 5 6]
 [6 9 2 3 5 1 8 7 4]
 [7 4 5 2 8 6 3 1 9]]
